# Form implementation generated from reading ui file '.\libs\ui\option.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 501)
        self.serialPortOption = QtWidgets.QComboBox(parent=Dialog)
        self.serialPortOption.setGeometry(QtCore.QRect(50, 40, 191, 41))
        self.serialPortOption.setObjectName("serialPortOption")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 60, 16))
        self.label.setObjectName("label")
        self.selectPort = QtWidgets.QPushButton(parent=Dialog)
        self.selectPort.setGeometry(QtCore.QRect(250, 40, 121, 41))
        self.selectPort.setObjectName("selectPort")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(50, 90, 561, 311))
        self.textBrowser.setObjectName("textBrowser")
        # self.enqBtn = QtWidgets.QPushButton(parent=Dialog)
        # self.enqBtn.setGeometry(QtCore.QRect(160, 420, 101, 41))
        # self.enqBtn.setObjectName("enqBtn")
        # self.ackBtn = QtWidgets.QPushButton(parent=Dialog)
        # self.ackBtn.setGeometry(QtCore.QRect(280, 420, 101, 41))
        # self.ackBtn.setObjectName("ackBtn")
        # self.eotBtn = QtWidgets.QPushButton(parent=Dialog)
        # self.eotBtn.setGeometry(QtCore.QRect(400, 420, 101, 41))
        # self.eotBtn.setObjectName("eotBtn")
        self.statusBtn = QtWidgets.QPushButton(parent=Dialog)
        self.statusBtn.setGeometry(QtCore.QRect(50, 420, 101, 41))
        self.statusBtn.setObjectName("statusBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "選擇串口"))
        self.label.setText(_translate("Dialog", "選擇串口"))
        self.selectPort.setText(_translate("Dialog", "Apply"))
        # self.enqBtn.setText(_translate("Dialog", "ENQ"))
        # self.ackBtn.setText(_translate("Dialog", "ACK"))
        # self.eotBtn.setText(_translate("Dialog", "EOT"))
        self.statusBtn.setText(_translate("Dialog", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
