# Form implementation generated from reading ui file 'libs/ui/option.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(424, 403)
        self.serialPortOption = QtWidgets.QComboBox(parent=Dialog)
        self.serialPortOption.setGeometry(QtCore.QRect(50, 40, 191, 41))
        self.serialPortOption.setObjectName("serialPortOption")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 60, 16))
        self.label.setObjectName("label")
        self.selectPort = QtWidgets.QPushButton(parent=Dialog)
        self.selectPort.setGeometry(QtCore.QRect(250, 40, 121, 41))
        self.selectPort.setObjectName("selectPort")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(50, 90, 341, 261))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "選擇串口"))
        self.selectPort.setText(_translate("Dialog", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
