# Form implementation generated from reading ui file 'libs/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(983, 523)
        self.testsTable = QtWidgets.QTableWidget(parent=dialog)
        self.testsTable.setGeometry(QtCore.QRect(20, 30, 801, 201))
        self.testsTable.setRowCount(0)
        self.testsTable.setColumnCount(2)
        self.testsTable.setObjectName("testsTable")
        item = QtWidgets.QTableWidgetItem()
        self.testsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.testsTable.setHorizontalHeaderItem(1, item)
        self.confirmBtn = QtWidgets.QPushButton(parent=dialog)
        self.confirmBtn.setGeometry(QtCore.QRect(840, 250, 91, 41))
        self.confirmBtn.setObjectName("confirmBtn")
        self.testsStartDate = QtWidgets.QDateEdit(parent=dialog)
        self.testsStartDate.setGeometry(QtCore.QRect(850, 50, 110, 22))
        self.testsStartDate.setObjectName("testsStartDate")
        self.searchBtn = QtWidgets.QPushButton(parent=dialog)
        self.searchBtn.setGeometry(QtCore.QRect(850, 130, 75, 41))
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.searchBtn.setCheckable(False)
        self.searchBtn.setChecked(False)
        self.searchBtn.setObjectName("searchBtn")
        self.testsEndDate = QtWidgets.QDateEdit(parent=dialog)
        self.testsEndDate.setGeometry(QtCore.QRect(850, 100, 110, 22))
        self.testsEndDate.setObjectName("testsEndDate")
        self.label_3 = QtWidgets.QLabel(parent=dialog)
        self.label_3.setGeometry(QtCore.QRect(850, 30, 47, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=dialog)
        self.label_4.setGeometry(QtCore.QRect(850, 80, 47, 16))
        self.label_4.setObjectName("label_4")
        self.resultsTable = QtWidgets.QTableWidget(parent=dialog)
        self.resultsTable.setGeometry(QtCore.QRect(20, 260, 801, 181))
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(5)
        self.resultsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultsTable.setHorizontalHeaderItem(4, item)
        self.option = QtWidgets.QPushButton(parent=dialog)
        self.option.setGeometry(QtCore.QRect(20, 480, 113, 32))
        self.option.setObjectName("option")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "G1200"))
        item = self.testsTable.horizontalHeaderItem(0)
        item.setText(_translate("dialog", "編號"))
        item = self.testsTable.horizontalHeaderItem(1)
        item.setText(_translate("dialog", "檢驗時間"))
        self.confirmBtn.setText(_translate("dialog", "確認上傳"))
        self.searchBtn.setText(_translate("dialog", "查詢"))
        self.label_3.setText(_translate("dialog", "開始日:"))
        self.label_4.setText(_translate("dialog", "結束日:"))
        item = self.resultsTable.horizontalHeaderItem(1)
        item.setText(_translate("dialog", "編號"))
        item = self.resultsTable.horizontalHeaderItem(2)
        item.setText(_translate("dialog", "檢驗結果"))
        item = self.resultsTable.horizontalHeaderItem(3)
        item.setText(_translate("dialog", "檢驗時間"))
        item = self.resultsTable.horizontalHeaderItem(4)
        item.setText(_translate("dialog", "已確認"))
        self.option.setText(_translate("dialog", "選擇串口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec())
